blank_issues_enabled: false
contact_links:
- name: Github Discussion
  url: https://github.com/HuanLinOTO/SVCHelper/discussions
  about: Asking for help here | 在讨论区寻求别人的帮助
- name: Official QQ Guild
  url: "https://jq.qq.com/?_wv=1027&k=N0wZJ5RK" 
  about: Asking for help from QQ Guild | 在官方QQ群寻求别人的帮助
