name: 拜九尾
description: 开始炼丹之前先拜拜九尾仙人～
title: "拜九尾: "
labels:
  - hope
body:
  - type: textarea
    attributes:
      label: Describe what model you will train
      description: 请简明地表述您在训练什么 (人物)。
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe what kind of 丹 you will train
      description: 说说你在炼什么丹 ( DiffSVC / SoVits 等等)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Problems
      description: 在遇到问题的时候，我承诺将所有问题在此 issue 提及 (即把 issue 的链接发到这个 issue)
      options: ["是","否"]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: 请描述其他想要补充的信息。
  - type: textarea
    attributes:
      label: None
      description: 祝你好运, 提问题之前看看这个吧(发送 issue 后查看)
      value: |
        - ![](https://i.328888.xyz/2023/02/03/NVRFk.png)
        - ![](https://i.328888.xyz/2023/02/03/NV3jx.png)
        - ![](https://i.328888.xyz/2023/02/03/NVcQL.jpeg)
